### ISSUE TITLE
GetMaterialPropertiesTable Type Error

### ISSUE THREAD

**Issue by jasqs** [HaarigerHarald/geant4_pybind#10]
Hi,

I wanted to define my own material, which I did successfully, but I wanted to change some its properties in the material properties table. I am getting an error, that python is **Unable to convert function return value to a Python type!**. 

A simple example:
```
import geant4_pybind as g4

nist = g4.G4NistManager.Instance()
waterMaterial = nist.FindOrBuildMaterial("G4_WATER",isotopes=False )
waterMaterial.GetMaterialPropertiesTable()
```

results in:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: Unregistered type : G4MaterialPropertiesTable

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Input In [2], in <cell line: 5>()
      3 nist = g4.G4NistManager.Instance()
      4 waterMaterial = nist.FindOrBuildMaterial("G4_WATER",isotopes=False )
----> 5 waterMaterial.GetMaterialPropertiesTable()

TypeError: Unable to convert function return value to a Python type! The signature was
	(self: geant4_pybind.G4Material) -> G4MaterialPropertiesTable
```

Also, there is no g4.G4MaterialPropertiesTable type defined.

I would appreciate help in this matter.

**Comment by HaarigerHarald** [comment]
Did you compile it yourself or are you using the PyPI version?

**Comment by jasqs** [comment]
> Did you compile it yourself or are you using the PyPI version?

I used PyPI version.

**Comment by HaarigerHarald** [comment]
That explains it, the PyPI version is a bit outdated. If you compile it from the current main branch it should work.

Furthermore, I'll try to push a new release to PyPI soon.

**Comment by jasqs** [comment]
I have successfully installed geant4_pybind from source including Geant4 installation and can confirm that the GetMaterialPropertiesTable is working now. I can test the PyPI version when it is available.
