### ISSUE TITLE
How to use it in multithreading mode?

### ISSUE THREAD

**Issue by Road-to-Serfdom** [HaarigerHarald/geant4_pybind#14]
When I run a complex program, I find that the program is running on just one thread, not on all the threads like Geant4 API. So can you tell me how to solve this problem?

**Comment by HaarigerHarald** [comment]
More or less Python is by design a [single threaded programming language](https://docs.python.org/3/glossary.html#term-global-interpreter-lock). That said, you might be able to achieve some parallelism by using the [multiprocessing module](https://docs.python.org/3/library/multiprocessing.html).
