### ISSUE TITLE
Geant4 datasets were not found

### ISSUE THREAD

**Issue by ahnaf-tahmid-chowdhury** [HaarigerHarald/geant4_pybind#16]
**Description:**
I'm encountering an issue with Geant4 Pybind where it's not utilizing the specified data directory for Geant4 datasets, even though I've downloaded the necessary data during the installation process.

**Environment:**
- Operating System: Ubuntu 23.04
- Python: 3.11.4
- Geant4: 11.1.2
- Geant4 Pybind: 0.1.0b13

**Steps to Reproduce:**
1. Configure Geant4 installation using the following CMake options:
   ```cmake
   cmake ../ -DCMAKE_INSTALL_PREFIX=$env_dir \
       -DGEANT4_USE_QT=ON \
       -DGEANT4_USE_OPENGL_X11=OFF \
       -DGEANT4_USE_SYSTEM_EXPAT=OFF \
       -DGEANT4_BUILD_TLS_MODEL=global-dynamic \
       -DGEANT4_BUILD_MULTITHREADED=ON \
       -DGEANT4_INSTALL_DATA=$install_geant4_data \
       -DGEANT4_INSTALL_DATADIR=$geant4_data_lib \
       -DGEANT4_INSTALL_DATA_TIMEOUT=0
   ```
2. Run the code importing Geant4 Pybind:
   ```python
   from geant4_pybind import *
   ```

**Expected Behavior:**
The Geant4 Pybind module should utilize the data directory specified using the `-DGEANT4_INSTALL_DATADIR` CMake option during installation (`$geant4_data_lib`), where the data was downloaded. It should not prompt to download the data again.

**Actual Behavior:**
Upon running the code, Geant4 Pybind prompts to download the missing datasets to `~/.geant4_pybind`, even though the data directory was specified during the installation process.

**Possible Solution:**
There might be an issue with how the data directory configuration is being interpreted by Geant4 Pybind. It's possible that there's a bug or misconfiguration causing this behavior.

Thank you for your attention to this matter. I'm looking forward to a resolution that allows Geant4 Pybind to utilize the specified data directory for Geant4 datasets.

**Comment by HaarigerHarald** [comment]
This happens if the environment variable `GEANT4_DATA_DIR` or alternatively the dataset specific environment variables weren't set. Did you source `geant4.sh`? This should set the necessary environment variables.

On Ubuntu you can run `export` to check whether `GEANT4_DATA_DIR` is set.

**Comment by ahnaf-tahmid-chowdhury** [comment]
Oh, it's working now. Thank you. However, I am in the process of building a package manager called [NuclearBoy](https://github.com/ahnaf-tahmid-chowdhury/NuclearBoy/tree/develop). I've observed that geant4-pybind is more recent than [g4python](https://github.com/koichi-murakami/g4python). I'm curious about the reasons behind having these two versions created. Moreover, I'm uncertain about which option might be the better choice for ensuring robustness.

Could you please assist me in understanding the motivations for having two versions? Additionally, any insights you can provide regarding which version could offer greater robustness and suitability for my project would be immensely helpful.

I appreciate your guidance!

**Comment by HaarigerHarald** [comment]
This was started before g4python was based on pybind11. In the old version of g4python one had to mix C++ with Python, I'm not sure whether this is still the case as I haven't used g4python since. I'd say just try both and see what works best for you.
