### ISSUE TITLE
LHEP PhysicsList

### ISSUE THREAD

**Issue by Zavyalov-github** [HaarigerHarald/geant4_pybind#25]
Good afternoon, esteemed developer!
I would like to extend my gratitude to you for creating an exceptional project that meets our needs perfectly.
I was wondering if there are any plans to incorporate support for the LHEP physics suite for parameterizing hadron interactions. If possible, I would greatly appreciate any updates on this matter.

**Comment by HaarigerHarald** [comment]
Could you pinpoint me to the C++ classes you are missing being bound to python?

**Comment by Zavyalov-github** [comment]
I apologize for the confusion. After closely examining the issue, I have determined that the LHEP module has been removed from Geant4 as of version 10.0. https://geant4.org/download/release-notes/notes-v10.0.0.html
