### ISSUE TITLE
Counting number of particle passed in certain volume.

### ISSUE THREAD

**Issue by saimegemenyucel** [HaarigerHarald/geant4_pybind#26]
Hi, I am trying to count the number of particle passed through my material and also the number of particles of how many of these particles reach to my germanium crystal inside my detector. I do not know which approach I should use. Can you help me with that please? Here is my code.

**Comment by HaarigerHarald** [comment]
One approach could be adding a `SensitiveDetector` to your germanium crystal's logical volume and processing the hits manually. This is exhibited in example B2.

Unfortunately I cannot offer support for specific projects or check your code, please consult with your supervisor if you have one.
