### ISSUE TITLE
[pyG4RayTracerX.cc] function 'export_G4RayTracerX' must have argument

### ISSUE THREAD

**Issue by vp1981** [HaarigerHarald/geant4_pybind#8]
Hello.

The function 'export_G4RayTracerX' in `pyG4RayTracerX.cc`
must have a mandatory argument, see e.g. the function `export_G4RayTracer` in `pyG4RayTracer.cc`. The line https://github.com/HaarigerHarald/geant4_pybind/blob/main/source/visualization/pyG4RayTracerX.cc#L13 should be as follows
```
void export_G4RayTracerX(py::module &m)
```

I faced that error when building package for Archlinux.

**Comment by HaarigerHarald** [comment]
Thanks, this should be fixed with 7033c51
